name: test-my-app

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install yq
        run: choco install yq

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml

      - run: flutter --version
      - run: flutter pub get
      - run: flutter test .\test\widget_test.dart
